version: 0.2

env:
  variables:
    DOCKER_BUILDKIT: "1"
    TARGET_ENV: "test"

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - export TARGET_ENV=${TARGET_ENV}
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - REPOSITORY_URI=あなたのリポジトリURI
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Spring Project...
      - ./gradlew build
      - echo Building the Docker image...
      - docker build --rm --no-cache  -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"名前","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
cache:
  paths:
    - '/root/.gradle/wrapper/**/*'
    - '/root/.gradle/caches/**/*'
